// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from './client';
import { client } from './client.gen';
import type { AddMediaApiMediaAddPostData, AddMediaApiMediaAddPostErrors, AddMediaApiMediaAddPostResponses, HealthCheckApiHealthGetData, HealthCheckApiHealthGetResponses, ListLibraryApiMediaLibraryGetData, ListLibraryApiMediaLibraryGetResponses, LoginApiAuthLoginPostData, LoginApiAuthLoginPostErrors, LoginApiAuthLoginPostResponses, ReadUsersMeApiAuthMeGetData, ReadUsersMeApiAuthMeGetResponses, RegisterApiAuthRegisterPostData, RegisterApiAuthRegisterPostErrors, RegisterApiAuthRegisterPostResponses, RemoveMediaApiMediaRemovePostData, RemoveMediaApiMediaRemovePostErrors, RemoveMediaApiMediaRemovePostResponses, RequestPasswordResetApiAuthRequestPasswordResetPostData, RequestPasswordResetApiAuthRequestPasswordResetPostErrors, RequestPasswordResetApiAuthRequestPasswordResetPostResponses, ResetPasswordApiAuthResetPasswordPostData, ResetPasswordApiAuthResetPasswordPostErrors, ResetPasswordApiAuthResetPasswordPostResponses, SearchMediaApiMediaSearchGetData, SearchMediaApiMediaSearchGetErrors, SearchMediaApiMediaSearchGetResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean, TResponse = unknown> = Options2<TData, ThrowOnError, TResponse> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

/**
 * Register
 *
 * Register a new user account.
 *
 * Args:
 * user_data: UserCreate schema with email, username, and password.
 * db: Database session.
 *
 * Returns:
 * UserResponse with the created user's details.
 *
 * Raises:
 * HTTPException: 400 Bad Request if email or username already exists.
 */
export const registerApiAuthRegisterPost = <ThrowOnError extends boolean = false>(options: Options<RegisterApiAuthRegisterPostData, ThrowOnError>) => (options.client ?? client).post<RegisterApiAuthRegisterPostResponses, RegisterApiAuthRegisterPostErrors, ThrowOnError>({
    url: '/api/auth/register',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Login
 *
 * Authenticate user with email and password, return JWT access token.
 *
 * Args:
 * login_data: LoginRequest schema with email and password.
 * db: Database session.
 *
 * Returns:
 * Token with access_token and token_type ("bearer").
 *
 * Raises:
 * HTTPException: 401 Unauthorized if email/password combination is invalid.
 */
export const loginApiAuthLoginPost = <ThrowOnError extends boolean = false>(options: Options<LoginApiAuthLoginPostData, ThrowOnError>) => (options.client ?? client).post<LoginApiAuthLoginPostResponses, LoginApiAuthLoginPostErrors, ThrowOnError>({
    url: '/api/auth/login',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Read Users Me
 *
 * Get the current authenticated user's profile information.
 *
 * Requires valid JWT token in Authorization header.
 *
 * Args:
 * current_user: Current authenticated user (injected via get_current_user).
 *
 * Returns:
 * UserResponse with the authenticated user's details.
 *
 * Raises:
 * HTTPException: 401 Unauthorized if no valid token provided.
 */
export const readUsersMeApiAuthMeGet = <ThrowOnError extends boolean = false>(options?: Options<ReadUsersMeApiAuthMeGetData, ThrowOnError>) => (options?.client ?? client).get<ReadUsersMeApiAuthMeGetResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/auth/me',
    ...options
});

/**
 * Request Password Reset
 *
 * Request a password reset token for the given email address.
 *
 * If an account exists, a reset token is generated (caller should send reset link via email).
 * Returns success message regardless to avoid email enumeration.
 *
 * Args:
 * email: Email address associated with the account.
 * db: Database session.
 *
 * Returns:
 * JSON message indicating reset link will be sent if account exists.
 *
 * Note:
 * Always returns success message to prevent user enumeration attacks.
 */
export const requestPasswordResetApiAuthRequestPasswordResetPost = <ThrowOnError extends boolean = false>(options: Options<RequestPasswordResetApiAuthRequestPasswordResetPostData, ThrowOnError>) => (options.client ?? client).post<RequestPasswordResetApiAuthRequestPasswordResetPostResponses, RequestPasswordResetApiAuthRequestPasswordResetPostErrors, ThrowOnError>({ url: '/api/auth/request-password-reset', ...options });

/**
 * Reset Password
 *
 * Reset a user's password using a valid reset token.
 *
 * Args:
 * token: Password reset token (obtained from password reset email).
 * new_password: New password to set for the account.
 * db: Database session.
 *
 * Returns:
 * JSON message confirming password has been reset.
 *
 * Raises:
 * HTTPException: 400 Bad Request if token is invalid, expired, or not found.
 */
export const resetPasswordApiAuthResetPasswordPost = <ThrowOnError extends boolean = false>(options: Options<ResetPasswordApiAuthResetPasswordPostData, ThrowOnError>) => (options.client ?? client).post<ResetPasswordApiAuthResetPasswordPostResponses, ResetPasswordApiAuthResetPasswordPostErrors, ThrowOnError>({ url: '/api/auth/reset-password', ...options });

/**
 * Health Check
 *
 * Health check endpoint for API availability monitoring.
 *
 * Can be used for:
 * - Load balancer health checks
 * - Kubernetes/container orchestration liveness probes
 * - Monitoring and alerting systems
 * - Uptime verification
 *
 * Returns:
 * JSON object with status "healthy" if API is running.
 */
export const healthCheckApiHealthGet = <ThrowOnError extends boolean = false>(options?: Options<HealthCheckApiHealthGetData, ThrowOnError>) => (options?.client ?? client).get<HealthCheckApiHealthGetResponses, unknown, ThrowOnError>({ url: '/api/health', ...options });

/**
 * Search Media
 *
 * Search Sonarr and Radarr for a title.
 *
 * Args:
 * term: Title (or partial title) to search for.
 *
 * Returns:
 * Combined TV and movie matches.
 *
 * Raises:
 * HTTPException: 502 if Sonarr/Radarr can't be reached.
 */
export const searchMediaApiMediaSearchGet = <ThrowOnError extends boolean = false>(options: Options<SearchMediaApiMediaSearchGetData, ThrowOnError>) => (options.client ?? client).get<SearchMediaApiMediaSearchGetResponses, SearchMediaApiMediaSearchGetErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/media/search',
    ...options
});

/**
 * List Library
 *
 * Return everything currently in the Sonarr and Radarr libraries.
 *
 * Raises:
 * HTTPException: 502 if Sonarr/Radarr can't be reached.
 */
export const listLibraryApiMediaLibraryGet = <ThrowOnError extends boolean = false>(options?: Options<ListLibraryApiMediaLibraryGetData, ThrowOnError>) => (options?.client ?? client).get<ListLibraryApiMediaLibraryGetResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/media/library',
    ...options
});

/**
 * Add Media
 *
 * Add a previously-searched title to the correct library and start
 * downloading it.
 *
 * Search results aren't cached server-side, so this re-runs the search
 * for `term` to locate the exact match by `media_type`/`external_id`
 * before adding it.
 *
 * Raises:
 * HTTPException: 404 if the match can no longer be found, 502 if the
 * backend rejects the add request.
 */
export const addMediaApiMediaAddPost = <ThrowOnError extends boolean = false>(options: Options<AddMediaApiMediaAddPostData, ThrowOnError>) => (options.client ?? client).post<AddMediaApiMediaAddPostResponses, AddMediaApiMediaAddPostErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/media/add',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Remove Media
 *
 * Remove a library item from whichever backend it belongs to.
 *
 * Raises:
 * HTTPException: 404 if no matching library item is found, 502 if the
 * backend rejects the remove request.
 */
export const removeMediaApiMediaRemovePost = <ThrowOnError extends boolean = false>(options: Options<RemoveMediaApiMediaRemovePostData, ThrowOnError>) => (options.client ?? client).post<RemoveMediaApiMediaRemovePostResponses, RemoveMediaApiMediaRemovePostErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/media/remove',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});
