// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://${string}` | (string & {});
};

/**
 * AddMediaRequest
 */
export type AddMediaRequest = {
    media_type: MediaType;
    /**
     * Term
     */
    term: string;
    /**
     * External Id
     */
    external_id: number;
    /**
     * Quality Profile Id
     */
    quality_profile_id?: number | null;
    /**
     * Root Folder Path
     */
    root_folder_path?: string | null;
    /**
     * Monitored
     */
    monitored?: boolean;
    /**
     * Search Now
     */
    search_now?: boolean;
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * LoginRequest
 */
export type LoginRequest = {
    /**
     * Email
     */
    email: string;
    /**
     * Password
     */
    password: string;
};

/**
 * MediaResultResponse
 */
export type MediaResultResponse = {
    media_type: MediaType;
    /**
     * Id
     */
    id: number;
    /**
     * Title
     */
    title: string;
    /**
     * Monitored
     */
    monitored: boolean;
    /**
     * External Id
     */
    external_id: number;
    /**
     * Year
     */
    year: number | null;
    /**
     * Overview
     */
    overview: string | null;
    /**
     * Poster Url
     */
    poster_url: string | null;
    /**
     * Fanart Url
     */
    fanart_url: string | null;
    /**
     * Genres
     */
    genres: Array<string>;
    /**
     * Runtime
     */
    runtime: number | null;
    /**
     * Rating
     */
    rating: number | null;
    /**
     * Network
     */
    network: string | null;
    /**
     * Studio
     */
    studio: string | null;
};

/**
 * MediaSearchResultResponse
 */
export type MediaSearchResultResponse = {
    media_type: MediaType;
    /**
     * Title
     */
    title: string;
    /**
     * Year
     */
    year: number | null;
    /**
     * Overview
     */
    overview: string | null;
    /**
     * Already In Library
     */
    already_in_library: boolean;
    /**
     * External Id
     */
    external_id: number;
    /**
     * Poster Url
     */
    poster_url: string | null;
    /**
     * Fanart Url
     */
    fanart_url: string | null;
    /**
     * Genres
     */
    genres: Array<string>;
    /**
     * Runtime
     */
    runtime: number | null;
    /**
     * Rating
     */
    rating: number | null;
    /**
     * Network
     */
    network: string | null;
    /**
     * Studio
     */
    studio: string | null;
};

/**
 * MediaType
 */
export type MediaType = 'series' | 'movie';

/**
 * RemoveMediaRequest
 */
export type RemoveMediaRequest = {
    media_type: MediaType;
    /**
     * Id
     */
    id: number;
    /**
     * Delete Files
     */
    delete_files?: boolean;
    /**
     * Add Exclusion
     */
    add_exclusion?: boolean;
};

/**
 * Token
 */
export type Token = {
    /**
     * Access Token
     */
    access_token: string;
    /**
     * Token Type
     */
    token_type: string;
};

/**
 * UserCreate
 */
export type UserCreate = {
    /**
     * Email
     */
    email: string;
    /**
     * Username
     */
    username: string;
    /**
     * Password
     */
    password: string;
};

/**
 * UserResponse
 */
export type UserResponse = {
    /**
     * Id
     */
    id: number;
    /**
     * Email
     */
    email: string;
    /**
     * Username
     */
    username: string;
    /**
     * Is Active
     */
    is_active: boolean;
    /**
     * Email Verified
     */
    email_verified: boolean;
    /**
     * Role
     */
    role: string;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Updated At
     */
    updated_at: string;
};

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
    /**
     * Input
     */
    input?: unknown;
    /**
     * Context
     */
    ctx?: {
        [key: string]: unknown;
    };
};

export type RegisterApiAuthRegisterPostData = {
    body: UserCreate;
    path?: never;
    query?: never;
    url: '/api/auth/register';
};

export type RegisterApiAuthRegisterPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type RegisterApiAuthRegisterPostError = RegisterApiAuthRegisterPostErrors[keyof RegisterApiAuthRegisterPostErrors];

export type RegisterApiAuthRegisterPostResponses = {
    /**
     * Successful Response
     */
    200: UserResponse;
};

export type RegisterApiAuthRegisterPostResponse = RegisterApiAuthRegisterPostResponses[keyof RegisterApiAuthRegisterPostResponses];

export type LoginApiAuthLoginPostData = {
    body: LoginRequest;
    path?: never;
    query?: never;
    url: '/api/auth/login';
};

export type LoginApiAuthLoginPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type LoginApiAuthLoginPostError = LoginApiAuthLoginPostErrors[keyof LoginApiAuthLoginPostErrors];

export type LoginApiAuthLoginPostResponses = {
    /**
     * Successful Response
     */
    200: Token;
};

export type LoginApiAuthLoginPostResponse = LoginApiAuthLoginPostResponses[keyof LoginApiAuthLoginPostResponses];

export type ReadUsersMeApiAuthMeGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/auth/me';
};

export type ReadUsersMeApiAuthMeGetResponses = {
    /**
     * Successful Response
     */
    200: UserResponse;
};

export type ReadUsersMeApiAuthMeGetResponse = ReadUsersMeApiAuthMeGetResponses[keyof ReadUsersMeApiAuthMeGetResponses];

export type RequestPasswordResetApiAuthRequestPasswordResetPostData = {
    body?: never;
    path?: never;
    query: {
        /**
         * Email
         */
        email: string;
    };
    url: '/api/auth/request-password-reset';
};

export type RequestPasswordResetApiAuthRequestPasswordResetPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type RequestPasswordResetApiAuthRequestPasswordResetPostError = RequestPasswordResetApiAuthRequestPasswordResetPostErrors[keyof RequestPasswordResetApiAuthRequestPasswordResetPostErrors];

export type RequestPasswordResetApiAuthRequestPasswordResetPostResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type ResetPasswordApiAuthResetPasswordPostData = {
    body?: never;
    path?: never;
    query: {
        /**
         * Token
         */
        token: string;
        /**
         * New Password
         */
        new_password: string;
    };
    url: '/api/auth/reset-password';
};

export type ResetPasswordApiAuthResetPasswordPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ResetPasswordApiAuthResetPasswordPostError = ResetPasswordApiAuthResetPasswordPostErrors[keyof ResetPasswordApiAuthResetPasswordPostErrors];

export type ResetPasswordApiAuthResetPasswordPostResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type HealthCheckApiHealthGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/health';
};

export type HealthCheckApiHealthGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type SearchMediaApiMediaSearchGetData = {
    body?: never;
    path?: never;
    query: {
        /**
         * Term
         */
        term: string;
    };
    url: '/api/media/search';
};

export type SearchMediaApiMediaSearchGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type SearchMediaApiMediaSearchGetError = SearchMediaApiMediaSearchGetErrors[keyof SearchMediaApiMediaSearchGetErrors];

export type SearchMediaApiMediaSearchGetResponses = {
    /**
     * Response Search Media Api Media Search Get
     *
     * Successful Response
     */
    200: Array<MediaSearchResultResponse>;
};

export type SearchMediaApiMediaSearchGetResponse = SearchMediaApiMediaSearchGetResponses[keyof SearchMediaApiMediaSearchGetResponses];

export type ListLibraryApiMediaLibraryGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/media/library';
};

export type ListLibraryApiMediaLibraryGetResponses = {
    /**
     * Response List Library Api Media Library Get
     *
     * Successful Response
     */
    200: Array<MediaResultResponse>;
};

export type ListLibraryApiMediaLibraryGetResponse = ListLibraryApiMediaLibraryGetResponses[keyof ListLibraryApiMediaLibraryGetResponses];

export type AddMediaApiMediaAddPostData = {
    body: AddMediaRequest;
    path?: never;
    query?: never;
    url: '/api/media/add';
};

export type AddMediaApiMediaAddPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type AddMediaApiMediaAddPostError = AddMediaApiMediaAddPostErrors[keyof AddMediaApiMediaAddPostErrors];

export type AddMediaApiMediaAddPostResponses = {
    /**
     * Successful Response
     */
    200: MediaResultResponse;
};

export type AddMediaApiMediaAddPostResponse = AddMediaApiMediaAddPostResponses[keyof AddMediaApiMediaAddPostResponses];

export type RemoveMediaApiMediaRemovePostData = {
    body: RemoveMediaRequest;
    path?: never;
    query?: never;
    url: '/api/media/remove';
};

export type RemoveMediaApiMediaRemovePostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type RemoveMediaApiMediaRemovePostError = RemoveMediaApiMediaRemovePostErrors[keyof RemoveMediaApiMediaRemovePostErrors];

export type RemoveMediaApiMediaRemovePostResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};
